feat: support npm, yarn, or pnpm in Dockerfiles and CI via lockfile detection; update docs

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,7 +28,12 @@ jobs:
         with:
           node-version: lts/*
       - name: Install dependencies
-        run: pnpm i --no-frozen-lockfile
+        run: |
+          if [ -f yarn.lock ]; then yarn install --no-immutable;
+          elif [ -f package-lock.json ]; then npm ci;
+          elif [ -f pnpm-lock.yaml ]; then pnpm i --no-frozen-lockfile;
+          else echo "Lockfile not found." && exit 1;
+          fi
       - name: Compile JSII
         run: pnpm projen compile
       - name: build
diff --git a/.github/workflows/cleanup-after-merge.yml b/.github/workflows/cleanup-after-merge.yml
--- a/.github/workflows/cleanup-after-merge.yml
+++ b/.github/workflows/cleanup-after-merge.yml
@@ -21,7 +21,13 @@ jobs:
         with:
           aws_account: ${{ vars.AWS_ACCOUNT }}
       - name: Cleanup global-functions
-        run: cd examples/global-functions && pnpm run destroy:ci
+        run: |
+          cd examples/global-functions
+          if [ -f yarn.lock ]; then yarn run destroy:ci;
+          elif [ -f package-lock.json ]; then npm run destroy:ci;
+          elif [ -f pnpm-lock.yaml ]; then pnpm run destroy:ci;
+          else echo "Lockfile not found." && exit 1;
+          fi
         continue-on-error: true
   cleanup-global-containers:
     needs: check-if-should-run
@@ -34,7 +40,13 @@ jobs:
         with:
           aws_account: ${{ vars.AWS_ACCOUNT }}
       - name: Cleanup global-containers
-        run: cd examples/global-containers && pnpm run destroy:ci
+        run: |
+          cd examples/global-containers
+          if [ -f yarn.lock ]; then yarn run destroy:ci;
+          elif [ -f package-lock.json ]; then npm run destroy:ci;
+          elif [ -f pnpm-lock.yaml ]; then pnpm run destroy:ci;
+          else echo "Lockfile not found." && exit 1;
+          fi
         continue-on-error: true
   cleanup-regional-containers:
     needs: check-if-should-run
@@ -47,7 +59,13 @@ jobs:
         with:
           aws_account: ${{ vars.AWS_ACCOUNT }}
       - name: Cleanup regional-containers
-        run: cd examples/regional-containers && pnpm run destroy:ci
+        run: |
+          cd examples/regional-containers
+          if [ -f yarn.lock ]; then yarn run destroy:ci;
+          elif [ -f package-lock.json ]; then npm run destroy:ci;
+          elif [ -f pnpm-lock.yaml ]; then pnpm run destroy:ci;
+          else echo "Lockfile not found." && exit 1;
+          fi
         continue-on-error: true
   cleanup-regional-functions:
     needs: check-if-should-run
@@ -60,5 +78,11 @@ jobs:
         with:
           aws_account: ${{ vars.AWS_ACCOUNT }}
       - name: Cleanup regional-functions
-        run: cd examples/regional-function && pnpm run destroy:ci
+        run: |
+          cd examples/regional-function
+          if [ -f yarn.lock ]; then yarn run destroy:ci;
+          elif [ -f package-lock.json ]; then npm run destroy:ci;
+          elif [ -f pnpm-lock.yaml ]; then pnpm run destroy:ci;
+          else echo "Lockfile not found." && exit 1;
+          fi
         continue-on-error: true
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -37,7 +37,12 @@ jobs:
         with:
           node-version: lts/*
       - name: Install dependencies
-        run: pnpm i --frozen-lockfile
+        run: |
+          if [ -f yarn.lock ]; then yarn install --immutable;
+          elif [ -f package-lock.json ]; then npm ci;
+          elif [ -f pnpm-lock.yaml ]; then pnpm i --frozen-lockfile;
+          else echo "Lockfile not found." && exit 1;
+          fi
       - name: Compile JSII
         run: pnpm projen compile
       - name: release
